<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        Employee::insert([
            [
                'id' => 1,
                'employee_no' => 'EMP001',
                'first_name' => 'Juan',
                'last_name' => 'Dela Cruz',
                'email' => 'juan@example.com',
                'phone' => '09171234567',
                'department_id' => 1,
                'position' => 'PHP Developer',
                'salary' => 35000.00,
                'hire_date' => '2025-01-15',
                'status' => 'active',
                'created_at' => '2026-06-14 06:46:25',
                'updated_at' => '2026-06-14 06:46:25',
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'employee_no' => 'EMP002',
                'first_name' => 'Maria',
                'last_name' => 'Santos',
                'email' => 'maria@example.com',
                'phone' => '09181234567',
                'department_id' => 2,
                'position' => 'HR Specialist',
                'salary' => 28000.00,
                'hire_date' => '2025-03-10',
                'status' => 'inactive',
                'created_at' => '2026-06-14 06:46:25',
                'updated_at' => '2026-06-14 10:15:10',
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'employee_no' => 'EMP003',
                'first_name' => 'Jose',
                'last_name' => 'Reyes',
                'email' => 'jose@example.com',
                'phone' => '09191234567',
                'department_id' => 3,
                'position' => 'Accountant',
                'salary' => 32000.00,
                'hire_date' => '2025-02-20',
                'status' => 'active',
                'created_at' => '2026-06-14 06:46:25',
                'updated_at' => '2026-06-14 09:40:35',
                'deleted_at' => '2026-06-14 09:40:35',
            ],
            [
                'id' => 4,
                'employee_no' => 'EMP004',
                'first_name' => 'Ana',
                'last_name' => 'Garcia',
                'email' => 'ana.garcia@example.com',
                'phone' => '09171234001',
                'department_id' => 1,
                'position' => 'Frontend Developer',
                'salary' => 34000.00,
                'hire_date' => '2024-06-01',
                'status' => 'active',
                'created_at' => '2026-06-14 10:13:53',
                'updated_at' => '2026-06-14 10:13:53',
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'employee_no' => 'EMP005',
                'first_name' => 'Carlo',
                'last_name' => 'Mendoza',
                'email' => 'carlo.mendoza@example.com',
                'phone' => '09171234002',
                'department_id' => 1,
                'position' => 'Backend Developer',
                'salary' => 36000.00,
                'hire_date' => '2024-07-15',
                'status' => 'active',
                'created_at' => '2026-06-14 10:13:53',
                'updated_at' => '2026-06-14 10:13:53',
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'employee_no' => 'EMP006',
                'first_name' => 'Liza',
                'last_name' => 'Torres',
                'email' => 'liza.torres@example.com',
                'phone' => '09171234003',
                'department_id' => 2,
                'position' => 'Recruiter',
                'salary' => 27000.00,
                'hire_date' => '2024-08-20',
                'status' => 'active',
                'created_at' => '2026-06-14 10:13:53',
                'updated_at' => '2026-06-14 10:13:53',
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'employee_no' => 'EMP007',
                'first_name' => 'Mark',
                'last_name' => 'Villanueva',
                'email' => 'mark.villanueva@example.com',
                'phone' => '09171234004',
                'department_id' => 2,
                'position' => 'HR Manager',
                'salary' => 42000.00,
                'hire_date' => '2023-11-05',
                'status' => 'active',
                'created_at' => '2026-06-14 10:13:53',
                'updated_at' => '2026-06-14 10:13:53',
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'employee_no' => 'EMP008',
                'first_name' => 'Grace',
                'last_name' => 'Lim',
                'email' => 'grace.lim@example.com',
                'phone' => '09171234005',
                'department_id' => 3,
                'position' => 'Finance Analyst',
                'salary' => 31000.00,
                'hire_date' => '2024-09-10',
                'status' => 'active',
                'created_at' => '2026-06-14 10:13:53',
                'updated_at' => '2026-06-14 10:13:53',
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'employee_no' => 'EMP009',
                'first_name' => 'Ryan',
                'last_name' => 'Castillo',
                'email' => 'ryan.castillo@example.com',
                'phone' => '09171234006',
                'department_id' => 3,
                'position' => 'Payroll Officer',
                'salary' => 29000.00,
                'hire_date' => '2025-01-08',
                'status' => 'active',
                'created_at' => '2026-06-14 10:13:53',
                'updated_at' => '2026-06-14 10:13:53',
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'employee_no' => 'EMP010',
                'first_name' => 'Sofia',
                'last_name' => 'Ramos',
                'email' => 'sofia.ramos@example.com',
                'phone' => '09171234007',
                'department_id' => 4,
                'position' => 'Marketing Associate',
                'salary' => 28000.00,
                'hire_date' => '2024-10-01',
                'status' => 'active',
                'created_at' => '2026-06-14 10:13:53',
                'updated_at' => '2026-06-14 10:13:53',
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'employee_no' => 'EMP011',
                'first_name' => 'Daniel',
                'last_name' => 'Navarro',
                'email' => 'daniel.navarro@example.com',
                'phone' => '09171234008',
                'department_id' => 4,
                'position' => 'Content Strategist',
                'salary' => 30000.00,
                'hire_date' => '2024-05-18',
                'status' => 'active',
                'created_at' => '2026-06-14 10:13:53',
                'updated_at' => '2026-06-14 10:13:53',
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'employee_no' => 'EMP012',
                'first_name' => 'Patricia',
                'last_name' => 'Bautista',
                'email' => 'patricia.bautista@example.com',
                'phone' => '09171234009',
                'department_id' => 1,
                'position' => 'QA Engineer',
                'salary' => 33000.00,
                'hire_date' => '2024-12-02',
                'status' => 'active',
                'created_at' => '2026-06-14 10:13:53',
                'updated_at' => '2026-06-14 10:13:53',
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'employee_no' => 'EMP013',
                'first_name' => 'Eric',
                'last_name' => 'Flores',
                'email' => 'eric.flores@example.com',
                'phone' => '09171234010',
                'department_id' => 3,
                'position' => 'Senior Accountant',
                'salary' => 38000.00,
                'hire_date' => '2023-03-22',
                'status' => 'inactive',
                'created_at' => '2026-06-14 10:13:53',
                'updated_at' => '2026-06-14 10:13:53',
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'employee_no' => 'EMP014',
                'first_name' => 'Hannah',
                'last_name' => 'Cruz',
                'email' => 'hannah.cruz@example.com',
                'phone' => '09171234011',
                'department_id' => 4,
                'position' => 'Social Media Manager',
                'salary' => 32000.00,
                'hire_date' => '2025-02-14',
                'status' => 'active',
                'created_at' => '2026-06-14 10:13:53',
                'updated_at' => '2026-06-14 10:13:53',
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'employee_no' => 'EMP015',
                'first_name' => 'Kevin',
                'last_name' => 'Aquino',
                'email' => 'kevin.aquino@example.com',
                'phone' => '09171234012',
                'department_id' => 1,
                'position' => 'DevOps Engineer',
                'salary' => 40000.00,
                'hire_date' => '2024-04-30',
                'status' => 'active',
                'created_at' => '2026-06-14 10:13:53',
                'updated_at' => '2026-06-14 10:13:53',
                'deleted_at' => null,
            ],
        ]);
    }
}
